title: Bryce Mecum
email: brycemecum@gmail.com
description: >-
  The personal site of Bryce Mecum
github_username: amoeba
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-archives
  - jekyll-gist
sass:
  style: compressed

include:
  - .well-known
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

collections:
  projects:
    output: true
    permalink: /:collection/:name
  teaching:
    output: true
    permalink: /:collection/:name
  talks:
    output: true
    permalink: /:collection/:name

jekyll-archives:
  enabled: all
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'
  layouts:
    year: archive-year
    month: archive-month
    day: archive-day
    tag: archive-tag
    category: archive-category
